trigger: none
pool:
  vmImage: ubuntu-latest

stages:
  - stage: initialise_values
    jobs:
      - job: initialise_values
        displayName: Initialse PR variables
        steps:
        - script: |
            sourceBranch=$(Build.SourceBranch)
            echo "== Source branch: $sourceBranch =="

            base_name=devci
            ci_cache_acr_name="acrdevci"
            tre_id="tre${base_name}"

            echo "##vso[task.setvariable variable=ci_cache_acr_name;isOutput=true]${ci_cache_acr_name}"
            echo "##vso[task.setvariable variable=tre_id;isOutput=true]${tre_id}"
            echo "##vso[task.setvariable variable=mgmt_resource_group;isOutput=true]rg-${tre_id}-mgmt"
            echo "##vso[task.setvariable variable=mgmt_storage_account;isOutput=true]sa${base_name}"
            echo "##vso[task.setvariable variable=mgmt_acr;isOutput=true]acr${base_name}"


          displayName: 'Generate TRE_ID'
          name: set_env_values

  - stage: start_tre
    dependsOn: initialise_values
    jobs:
    - job: tre_start
      variables:
      - group: DEV
      - name: tre_id
        value: $[ stageDependencies.initialise_values.initialise_values.outputs['set_env_values.tre_id'] ]
      - name: mgmt_resource_group
        value: $[ stageDependencies.initialise_values.initialise_values.outputs['set_env_values.mgmt_resource_group'] ]
      - name: mgmt_storage_account
        value: $[ stageDependencies.initialise_values.initialise_values.outputs['set_env_values.mgmt_storage_account'] ]
      - name: mgmt_acr
        value: $[ stageDependencies.initialise_values.initialise_values.outputs['set_env_values.mgmt_acr'] ]
      steps:
        - script: |
            set -e

            echo "Sign in to az"
            az login --service-principal --user "$(ARM_CLIENT_ID)" --password "$(ARM_CLIENT_SECRET)" --tenant "$(ARM_TENANT_ID)"

            echo "Set subscription"
            az account set --subscription "$(ARM_SUBSCRIPTION_ID)"
          displayName: az login

        - task: DevcontainersCi@0
          displayName: Start TRE
          inputs:
            imageName: ouhtre-deployment-devcontainer
            # skip image push here as we're just re-using the image rather than building it
            push: never
            runCmd: make tre-start
            env: |
              AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
              ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID=$(ARM_TENANT_ID)
              AAD_TENANT_ID=$(ARM_TENANT_ID)
              LOCATION=uksouth
              TF_VAR_arm_client_id=$(ARM_CLIENT_ID)
              TF_VAR_arm_client_secret=$(ARM_CLIENT_SECRET)
              TF_VAR_arm_subscription_id=$(ARM_SUBSCRIPTION_ID)
              TF_VAR_arm_tenant_id=$(ARM_TENANT_ID)
              TF_VAR_aad_tenant_id=$(ARM_TENANT_ID)
              TF_VAR_location=uksouth
              TF_VAR_mgmt_resource_group_name=$(mgmt_resource_group)
              TF_VAR_mgmt_storage_account_name=$(mgmt_storage_account)
              TF_VAR_acr_name=$(mgmt_acr)
              TF_VAR_terraform_state_container_name=tfstate
              TF_VAR_api_client_id=$(API_CLIENT_ID)
              TF_VAR_api_client_secret=$(API_CLIENT_SECRET)
              TF_VAR_application_admin_client_id=$(APPLICATION_ADMIN_CLIENT_ID)
              TF_VAR_application_admin_client_secret=$(APPLICATION_ADMIN_CLIENT_SECRET)
              TF_VAR_core_address_space=$(CORE_ADDRESS_SPACE)
              TF_VAR_tre_address_space=$(TRE_ADDRESS_SPACE)
              TF_VAR_resource_processor_type=$(RESOURCE_PROCESSOR_TYPE)
              TF_VAR_api_app_service_plan_sku_size=$(API_APP_SERVICE_PLAN_SKU_SIZE)
              TF_VAR_enable_airlock_malware_scanning=$(ENABLE_AIRLOCK_MALWARE_SCANNING)
              TF_VAR_swagger_ui_client_id=$(SWAGGER_UI_CLIENT_ID)
              TF_VAR_tre_id=$(tre_id)
              TF_VAR_ci_git_ref=$(Build.SourceBranch)
              DEBUG="false"
              TRE_ID=$(tre_id)
              USE_ENV_VARS_NOT_FILES=true
              TF_IN_AUTOMATION=true
              ACR_NAME=$(MGMT_ACR)
              CI_CACHE_ACR_NAME=$(ci_cache_acr_name)
              DEPLOY_UI=true
              SWAGGER_UI_CLIENT_ID=$(SWAGGER_UI_CLIENT_ID)
              API_CLIENT_ID=$(API_CLIENT_ID)
              API_CLIENT_SECRET=$(API_CLIENT_SECRET)
              LETSENCRYPT_DROP_ALL_RULES=1

